services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
  
  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes: 
      - ./app:/var/www/html
      - ./app/data:/var/www/html/data
    depends_on:
      - db
    
  db: 
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer 
    restart: always 
    ports: 
      - "8181:8080"
    environment: 
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  db_data: