services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./tmp:/tmp/mpdf
    working_dir: /var/www/html
    depends_on:
      - db
    env_file:
      - .env
    
  db: 
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data_bookstore:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer 
    restart: always 
    ports: 
      - "8181:8080"
    environment: 
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  db_data_bookstore: